m2w64_c_compiler:                 # [win]
- gcc                             # [win]
m2w64_c_compiler_version:         # [win]
- '14'                            # [win]
m2w64_cxx_compiler:               # [win]
- gxx                             # [win]
m2w64_cxx_compiler_version:       # [win]
- '14'                            # [win]
m2w64_fortran_compiler:           # [win]
- gfortran                        # [win]
m2w64_fortran_compiler_version:   # [win]
- '14'                            # [win]
